[project]
name = "big-data-proj"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "tensorflow>=2.19.0",
    "scikit-learn>=1.6.1",
    "matplotlib>=3.10.3",
]
